const BALL_COUNT = 50;
const CONTAINER_WIDTH = 1000;
const CONTAINER_HEIGHT = 750;
const FRAMERATE = 60; //in ms
const PHYSICS_STEP = 15; //in ms
const MIN_R = 10;
const MAX_R = 35;

export {
  BALL_COUNT,
  CONTAINER_HEIGHT,
  CONTAINER_WIDTH,
  FRAMERATE,
  PHYSICS_STEP,
  MIN_R,
  MAX_R,
};
